export const meta = {
  name: 'xr-timeline-stage2-r4',
  description: 'Round 4: dedupe verified rows (primary copies, regulatory, trade, HKEX, Newsweb, Program B), update synthesis + CMD questions + watch list, skeptic panel, repair, critique',
  phases: [
    { title: 'Dedupe', detail: 'round-4 rows vs existing rows, per lane (Sonnet)' },
    { title: 'Synthesize', detail: 'findings, matches, estimate, CMD questions, watch list; commentary and lead-time patches' },
    { title: 'Challenge', detail: 'three skeptic lenses (evidence, logic, arithmetic) per group of findings and on the estimate' },
    { title: 'Repair', detail: 'rewrite findings, estimate, matches to answer every surviving challenge' },
    { title: 'Critique', detail: 'completeness critic: what the dataset still lacks' },
  ],
}
const D = args.dir
const LANES = `producer: meta, apple, google, samsung, snap, xreal, rokid, rayneo, even, amazon, alibaba, xiaomi, otheroem; supplier/evidence: polight, qtech, cml, optotune, varioptic, sheba, vcm, modules, metaip (Meta patents & people), analysts`
const DEDUPE_SCHEMA = { type: 'object', required: ['drop', 'fix'], properties: {
  drop: { type: 'array', items: { type: 'string' }, description: 'ids of NEW rows that duplicate an existing row or another new row' },
  fix: { type: 'array', items: { type: 'object', required: ['id', 'field', 'value'], properties: { id: { type: 'string' }, field: { type: 'string', enum: ['date', 'precision', 'conf', 'cat', 'type', 'lane', 'start', 'end', 'url', 'detail', 'title'] }, value: { type: 'string' } } } } } }

phase('Dedupe')
const jobs = args.lanes.map(l => () => agent(
`Two JSON files describe timeline rows for lane "${l}" of a research dataset: ${D}/existing/lane_${l}.json (rows already in the published map) and ${D}/new/lane_${l}.json (round-4 rows from primary-document retrieval, public LinkedIn/job-post checks, regulatory filings, trade data, Q Tech HKEX filings, poLight Newsweb filings and a Program B candidate study; their detail may carry "[Source check: ...]" notes from two independent fact-checkers). Read both; judge the NEW rows. (a) Return ids of NEW rows to DROP because they restate a fact already in the existing rows or another new row — EXCEPT when the new row is a primary-source verification of an existing row that is tagged rumor/circumstantial or lacks a primary URL: then DROP the new row AND return fixes on the EXISTING row's id that upgrade it (field conf → the level the new evidence supports; field url → the new primary URL; field detail → the existing detail followed by " [Primary copy, round 4: " + the verbatim evidence + "]"). (b) DROP new rows whose source check says the claim is not supported or no source was found, unless they record a useful negative result already worded as one. (c) Keep genuinely new facts even if minor. (c2) If a new row CONTRADICTS an existing row with better (primary) evidence — e.g. a different owner, date, amount or wording — keep the new row and return fixes on the EXISTING row: conf → "rumor" and detail → the existing detail followed by " [Contradicted in round 4: " + what the primary source says + "]". (d) Fixes on new rows: precision must match the date format (YYYY-MM-DD=day, YYYY-MM=month, YYYY-Qn=quarter, YYYY-Hn=half, YYYY=year); wrong lane per ${LANES}; wrong cat (product = device releases/announcements/roadmap; commercial = orders, design-in, qualification, capacity, partnership, financing, earnings, insider trades, holdings; ip = patents, hires, papers, talks, job posts, profiles; press = analyst/press/rumour; regulatory filings = product).`,
  { label: `dedupe:${l}`, phase: 'Dedupe', schema: DEDUPE_SCHEMA, effort: 'medium', model: 'sonnet' }))
const winJob = () => agent(`Read ${D}/existing/windows.json (windows already in the map) and ${D}/new/windows.json (new). Return ids of NEW windows that duplicate an existing or another new window (same product/launch/claim in the same lane), and fixes for wrong lane or start>end.`, { label: 'dedupe:windows', phase: 'Dedupe', schema: DEDUPE_SCHEMA, effort: 'medium', model: 'sonnet' })
const ded = await parallel([...jobs, winJob])
const dropSet = new Set(); const fixes = []
ded.filter(Boolean).forEach(r => { r.drop.forEach(x => dropSet.add(x)); fixes.push(...r.fix) })
log(`dedupe: ${dropSet.size} new rows dropped, ${fixes.length} fixes`)

phase('Synthesize')
const MATCH_ITEMS = { type: 'array', items: { type: 'object', required: ['from', 'to', 'title', 'comment', 'strength'], properties: { from: { type: 'string' }, to: { type: 'string' }, title: { type: 'string' }, comment: { type: 'string' }, strength: { type: 'string', enum: ['confirmed', 'strong', 'circumstantial', 'rumor'] } } } }
const EST = { type: 'object', required: ['p_tlens_in_meta_vr_glasses', 'p_meta_is_qtech_backed_oem', 'reasoning'], properties: { p_tlens_in_meta_vr_glasses: { type: 'number' }, p_meta_is_qtech_backed_oem: { type: 'number' }, reasoning: { type: 'string' } } }
const CPATCH = { type: 'array', items: { type: 'object', required: ['lane', 'title', 'start', 'end', 'text'], properties: { lane: { type: 'string' }, title: { type: 'string' }, start: { type: 'string' }, end: { type: 'string' }, text: { type: 'string' } } } }
const LPATCH = { type: 'array', items: { type: 'object', required: ['window', 'lanes', 'phases', 'rationale'], properties: { window: { type: 'string' }, lanes: { type: 'array', items: { type: 'string' } }, phases: { type: 'array', items: { type: 'object', required: ['label', 'start', 'end'], properties: { label: { type: 'string' }, start: { type: 'string' }, end: { type: 'string' } } } }, rationale: { type: 'string' } } } }
const CMDQ = { type: 'array', items: { type: 'object', required: ['question', 'why', 'if_yes', 'if_no'], properties: { question: { type: 'string' }, why: { type: 'string' }, if_yes: { type: 'string' }, if_no: { type: 'string' } } } }
const WATCH = { type: 'array', items: { type: 'object', required: ['date_from', 'date_to', 'what', 'where', 'if_positive', 'if_negative'], properties: { date_from: { type: 'string' }, date_to: { type: 'string' }, what: { type: 'string' }, where: { type: 'string' }, if_positive: { type: 'string' }, if_negative: { type: 'string' } } } }
const CORE_SCHEMA = { type: 'object', required: ['headline_findings', 'estimate', 'matches', 'subtitle', 'foot', 'cmd_questions', 'watchlist'], properties: { headline_findings: { type: 'array', items: { type: 'string' } }, estimate: EST, matches: MATCH_ITEMS, subtitle: { type: 'string' }, foot: { type: 'string' }, cmd_questions: CMDQ, watchlist: WATCH } }
const PATCH_SCHEMA = { type: 'object', required: ['commentary_patches', 'leadtime_patches'], properties: { commentary_patches: CPATCH, leadtime_patches: LPATCH } }
const CONTEXT = `You are updating the synthesis layer of a timeline map (today 2026-10-08) for a poLight ASA shareholder asking whether poLight's TLens is in Meta's spring-2027 VR Glasses and how poLight and competing autofocus suppliers line up with producers' launches. Read: ${D}/existing/synthesis.json (current lead-times, matches, commentary per lane, headline findings, subtitle, foot, estimate — the round-3 state: 0.58 TLens in VR Glasses, 0.78 Meta is the Q Tech-backed OEM), ${D}/existing/compact.json (all existing events), ${D}/existing/windows.json, ${D}/new/compact.json (round-4 rows: primary copies of the DBS page and Meta's developer page, the public LinkedIn and job-post trail, Meta's regulatory filing history and expected VR Glasses filings, trade/shipment evidence, Q Tech HKEX filings, poLight Newsweb insider/holder/short data and new Q&A answers, and the Program B candidate study; ignore ids in this dropped list: ${JSON.stringify([...dropSet])}), ${D}/new/windows.json, ${D}/new/verification_summary.txt (two independent fact-checkers per load-bearing row), and the round-4 research files ${args.research_files.join(', ')} (read their Gaps sections: documented "not publicly available" results matter). Lanes: ${LANES}. Upgrades of existing rows by primary copies count as evidence quality changes, not new evidence; do not double-count them.`
const CORE_PROMPT = `${CONTEXT}
Return ONLY these parts of the updated synthesis (another agent updates commentary and lead-times): (1) matches — the FULL updated list: keep existing matches that are still right, revise wrong ones, add matches for round-4 signals (e.g. a Meta regulatory filing window → the VR Glasses launch; Q Tech HKEX disclosures → the Q Tech TLens ramp; Program B candidates → poLight's Program B POs; verified LinkedIn items → Meta's AF program) with honest strengths; from/to must be ids present in the files; comments ≤ 45 words; (2) headline_findings — 10–14 self-contained paragraphs (60–120 words) with dates and the strongest primary sources, no row ids; revise the round-3 findings where round 4 changes evidence quality (e.g. a primary copy of the DBS page or Meta's developer page, LinkedIn items now verified or still unverifiable), and add what the hard-evidence sweep found or failed to find (regulatory, trade, HKEX, Newsweb) and what Program B most likely is; (3) estimate — probabilities (0–1) for TLens in Meta VR Glasses at launch and for Meta being the Q Tech-backed OEM, with 6–10 sentences of reasoning citing dated evidence and stating explicitly how round 4 moves each number relative to round 3 (0.58 and 0.78) and why — evidence-quality upgrades can move a number only through the weight that item already carried; (4) subtitle (≤ 60 words) and foot (≤ 80 words); (5) cmd_questions — 8–12 precise questions a shareholder could put to poLight's CEO at the Q3 report (2026-10-29) and Capital Markets Day (2026-10-30), each answerable without breaching customer NDAs (e.g. Program A stage: still "qualification" or design-in; whether qualification POs became production POs; whether the Philippines units are for Program A; Program C device class and timing; wafer orders; capacity at Q Tech; whether Program B shipped and its volumes; how poLight will disclose a design-win), with why it matters and how a yes/no answer would move the estimate; (6) watchlist — 10–16 dated hard-evidence checks for 2026-10 to 2027-06 (regulatory filings for the VR Glasses and puck, Q Tech monthly volumes and results, poLight Q3/Q4 reports and Newsweb notices, insider and short-position changes, trade-data checks, teardown dates for Program B candidates and the VR Glasses, CES/MWC/SPIE), each with date_from/date_to (YYYY-MM-DD), what to check, where (URL or register), and what a positive or negative result would mean.`
const PATCH_PROMPT = `${CONTEXT}
Return ONLY patches to the per-lane commentary and the lead-time entries (another agent handles findings, matches and the estimate). commentary_patches: for every lane round 4 touches (meta, metaip, polight, qtech, modules, analysts, otheroem, alibaba, snap, samsung and any other lane with new rows) give replacement or new segments — each with lane, the segment title (reuse an existing title to replace that segment, or a new title to add one), start/end dates (YYYY-MM-DD) and 80–160 words of text that says what that stretch of the timeline indicates, including cadence (gaps between filings/updates) and what the evidence does NOT show; write the meta segment on the primary copy of the developer page and the regulatory filing cadence, the metaip segment on what the public LinkedIn/job-post trail verifies, the qtech segment on the HKEX disclosures (monthly volumes, associate note, connected transactions), the polight segment on insider/holder/short behaviour and the latest CEO answers, and segments on the Program B candidates in their producer lanes. leadtime_patches: only if round-4 evidence changes a phase of an existing lead-time entry (e.g. regulatory-filing lags for the VR Glasses) (window id must exist) — otherwise return an empty array. Use only ids present in the files.`
const synthJobs = await parallel([
  async () => { let r = await agent(CORE_PROMPT, { label: 'synth:core', phase: 'Synthesize', schema: CORE_SCHEMA, effort: 'max' }); for (let k = 1; !r && k <= 3; k++) { log(`synth:core returned null — retry ${k}`); r = await agent(CORE_PROMPT, { label: `synth:core:retry${k}`, phase: 'Synthesize', schema: CORE_SCHEMA, effort: 'max' }) } return r },
  async () => { let r = await agent(PATCH_PROMPT, { label: 'synth:patches', phase: 'Synthesize', schema: PATCH_SCHEMA, effort: 'high' }); for (let k = 1; !r && k <= 3; k++) { log(`synth:patches returned null — retry ${k}`); r = await agent(PATCH_PROMPT, { label: `synth:patches:retry${k}`, phase: 'Synthesize', schema: PATCH_SCHEMA, effort: 'high' }) } return r },
])
const core = synthJobs[0], patches = synthJobs[1] || { commentary_patches: [], leadtime_patches: [] }
if (!core) throw new Error('synthesis core failed after retries')
const syn = { headline_findings: core.headline_findings, estimate: core.estimate, matches: core.matches, subtitle: core.subtitle, foot: core.foot, commentary_patches: patches.commentary_patches, leadtime_patches: patches.leadtime_patches }
log(`synthesis: ${syn.matches.length} matches, ${syn.headline_findings.length} findings, ${syn.commentary_patches.length} commentary patches, ${syn.leadtime_patches.length} lead-time patches, estimate ${syn.estimate.p_tlens_in_meta_vr_glasses}/${syn.estimate.p_meta_is_qtech_backed_oem}`)

phase('Challenge')
const ISSUE_SCHEMA = { type: 'object', required: ['issues'], properties: { issues: { type: 'array', items: { type: 'object', required: ['finding_index', 'claim', 'problem', 'severity', 'fix'], properties: { finding_index: { type: 'integer', description: '0-based index into the findings list you were given; -1 for the estimate' }, claim: { type: 'string' }, problem: { type: 'string' }, severity: { type: 'string', enum: ['blocking', 'minor'] }, fix: { type: 'string', description: 'the corrected wording or the row ids/dates that support the claim' } } } } } }
const F = syn.headline_findings
const groups = []
for (let i = 0; i < F.length; i += 3) groups.push({ kind: 'findings', start: i, items: F.slice(i, i + 3) })
groups.push({ kind: 'estimate', start: -1, items: [JSON.stringify(syn.estimate)] })
const FILES = `${D}/existing/compact.json (the existing dated rows: id, lane, date, cat, type, title, conf, key), ${D}/new/compact.json (patent-sweep rows with register-check notes), ${D}/existing/windows.json, ${D}/new/windows.json, ${D}/new/verification_summary.txt, and ${D}/existing/synthesis.json (the previous round's synthesis, for comparison)`
const LENSES = {
  evidence: (g) => `You are a skeptical EVIDENCE auditor. Read ${FILES}. Below are ${g.kind === 'estimate' ? 'the probability estimate and its reasoning' : 'headline findings'} drafted from that dataset (today 2026-10-08). For EVERY factual claim in them (a date, an amount, a quoted phrase, a count such as "four applications", an attribution such as "Meta said" vs "an analyst wrote"), find the supporting dated row(s) in the files. Report every claim you cannot locate, every date or number that differs from the row, every quoted phrase that is not in a row's title/detail, and every attribution that upgrades an analyst/press/forum/job-post source into a company statement. Default to suspicion: if you cannot find it, it is an issue. finding_index is the 0-based index within the list below${g.kind === 'estimate' ? ' (use -1)' : ` plus ${g.start}`}. Severity blocking = the claim is unsupported or wrong; minor = imprecise but defensible.\n\n${g.items.map((t, i) => `[${g.kind === 'estimate' ? -1 : g.start + i}] ${t}`).join('\n\n')}`,
  logic: (g) => `You are a skeptical LOGIC auditor (think: a short-seller's analyst reading a bull case). Read ${FILES}. Below are ${g.kind === 'estimate' ? 'the probability estimate and its reasoning' : 'headline findings'} drafted from that dataset (today 2026-10-08). Attack the inferences: does the conclusion follow from the cited facts; is a patent that names "TLens" as one option being read as a supply relationship; is an assembler's filing being attributed to its customer; are alternative explanations (Meta building its own membrane lens, VCM, another supplier, a different product) acknowledged where the evidence allows them; are hedges proportional to source quality; is anything stated with more certainty than the rows' confidence levels allow; does the estimate's reasoning double-count the same evidence or ignore the strongest counter-evidence in the dataset (list it). Report each over-reach as an issue with a fix that states what the evidence actually supports. finding_index is the 0-based index within the list below${g.kind === 'estimate' ? ' (use -1)' : ` plus ${g.start}`}. Severity blocking = the inference is not supported; minor = wording should be hedged.\n\n${g.items.map((t, i) => `[${g.kind === 'estimate' ? -1 : g.start + i}] ${t}`).join('\n\n')}`,
  arithmetic: (g) => `You are a skeptical DATES-AND-ARITHMETIC auditor. Read ${FILES}. Below are ${g.kind === 'estimate' ? 'the probability estimate and its reasoning' : 'headline findings'} drafted from that dataset (today 2026-10-08). Recompute every interval ("N months before launch", "within 15 days", "14 months", "4.8–10 months"), every count ("four 2024 applications", "about 35 hits", "70 publications"), every ordering claim ("first", "only", "earliest", "latest") and every lead-time statement against the dated rows and windows; check that the Meta VR Glasses launch window used is the one in the dataset; check priority vs filing vs publication vs grant dates are not conflated. Report each discrepancy with the correct figure and the row ids/dates you used. finding_index is the 0-based index within the list below${g.kind === 'estimate' ? ' (use -1)' : ` plus ${g.start}`}. Severity blocking = a number or date is wrong; minor = rounding or ambiguity.\n\n${g.items.map((t, i) => `[${g.kind === 'estimate' ? -1 : g.start + i}] ${t}`).join('\n\n')}`,
}
const jobsC = groups.flatMap((g) => Object.keys(LENSES).map(lens => ({ g, lens, label: `challenge:${g.kind === 'estimate' ? 'estimate' : 'f' + g.start}:${lens}` })))
const runC = (suffix) => (j) => () => agent(LENSES[j.lens](j.g), { label: j.label + suffix, phase: 'Challenge', schema: ISSUE_SCHEMA, effort: 'high', model: 'sonnet' }).then(r => (r && r.issues ? r.issues.map(x => ({ ...x, lens: j.lens })) : null))
let challenge = await parallel(jobsC.map(runC('')))
let missing = jobsC.filter((j, i) => !challenge[i])
if (missing.length) { log(`challenge: ${missing.length} skeptics returned nothing — retrying them once`); const again = await parallel(missing.map(runC(':retry1'))); missing.forEach((j, k) => { const i = jobsC.indexOf(j); challenge[i] = again[k] }) }
const stillMissing = jobsC.filter((j, i) => !challenge[i]).map(j => j.label)
if (stillMissing.length > 3) throw new Error(`challenge incomplete: ${stillMissing.length} skeptics failed (${stillMissing.join(', ')}) — resume later from cache`)
if (stillMissing.length) log(`challenge: proceeding without ${stillMissing.join(', ')}`)
const issues = challenge.filter(Boolean).flat()
const blocking = issues.filter(x => x.severity === 'blocking')
log(`challenge: ${issues.length} issues (${blocking.length} blocking) from ${groups.length * 3} skeptics`)

phase('Repair')
const REPAIR_SCHEMA = { type: 'object', required: ['headline_findings', 'estimate', 'matches', 'commentary_patches', 'leadtime_patches', 'subtitle', 'foot', 'changes_made', 'cmd_questions', 'watchlist'], properties: {
  cmd_questions: CMDQ, watchlist: WATCH,
  headline_findings: { type: 'array', items: { type: 'string' } },
  estimate: EST,
  matches: MATCH_ITEMS,
  commentary_patches: { type: 'array', items: { type: 'object', required: ['lane', 'title', 'start', 'end', 'text'], properties: { lane: { type: 'string' }, title: { type: 'string' }, start: { type: 'string' }, end: { type: 'string' }, text: { type: 'string' } } }, description: 'segments to replace (same lane+title) or add; leave empty if none' },
  leadtime_patches: { type: 'array', items: { type: 'object', required: ['window', 'lanes', 'phases', 'rationale'], properties: { window: { type: 'string' }, lanes: { type: 'array', items: { type: 'string' } }, phases: { type: 'array', items: { type: 'object', required: ['label', 'start', 'end'], properties: { label: { type: 'string' }, start: { type: 'string' }, end: { type: 'string' } } } }, rationale: { type: 'string' } } }, description: 'lead-time entries to replace (same window) or add; leave empty if none' },
  subtitle: { type: 'string' }, foot: { type: 'string' },
  changes_made: { type: 'array', items: { type: 'string' }, description: 'one line per issue: what you changed, or why you kept the text (with the row ids that support it)' } } }
const REP_PROMPT = 
`You are the editor of record for the synthesis layer of a timeline map (today 2026-10-08). Three independent skeptics (evidence, logic, dates-and-arithmetic) audited the draft headline findings and the probability estimate below against the dataset files: ${FILES}. Your job: produce the corrected synthesis. Rules: (1) every BLOCKING issue must be resolved — fix the claim, re-hedge it, or delete it; you may keep text unchanged only if you re-verify it in the files and say so in changes_made with the row ids; (2) resolve minor issues where the fix is clear; (3) keep 10–14 findings, each a self-contained paragraph with dates and the strongest primary sources, no row ids in the prose; (4) return the full corrected matches list (edit, remove or add entries; ids must exist in the files; from/to are row or window ids; strengths honest); (5) commentary_patches and leadtime_patches: return the draft patches above, corrected where an issue touched them, plus any new patch an issue requires (they replace or add segments/entries in the existing synthesis file); (6) re-state the estimate with reasoning that answers the skeptics' strongest counter-evidence explicitly, moving the numbers only as far as the evidence warrants; (7) return cmd_questions and watchlist, corrected where an issue touched them (dates must be right; questions must not presuppose unproven facts); (8) list changes_made.

DRAFT FINDINGS (0-based index):
${F.map((t, i) => `[${i}] ${t}`).join('\n\n')}

DRAFT ESTIMATE: ${JSON.stringify(syn.estimate)}

DRAFT MATCHES: ${JSON.stringify(syn.matches)}

DRAFT COMMENTARY PATCHES (applied on top of the commentary in ${D}/existing/synthesis.json, which you should read for the unchanged lanes): ${JSON.stringify(syn.commentary_patches)}

DRAFT LEAD-TIME PATCHES (applied on top of the lead-times in that same file): ${JSON.stringify(syn.leadtime_patches)}

CMD QUESTIONS: ${JSON.stringify(core.cmd_questions)}

WATCH LIST: ${JSON.stringify(core.watchlist)}

SUBTITLE: ${syn.subtitle}
FOOT: ${syn.foot}

ISSUES RAISED (${issues.length}; ${blocking.length} blocking):
${JSON.stringify(issues)}`

let rep = await agent(REP_PROMPT, { label: 'repair', phase: 'Repair', schema: REPAIR_SCHEMA, effort: 'max', model: 'sonnet' })
for (let k = 1; !rep && k <= 3; k++) { log(`repair returned null — retry ${k}`); rep = await agent(REP_PROMPT, { label: `repair:retry${k}`, phase: 'Repair', schema: REPAIR_SCHEMA, effort: 'max', model: 'sonnet' }) }
if (!rep) throw new Error('repair failed after retries')
log(`repair: ${rep.headline_findings.length} findings, ${rep.matches.length} matches, ${rep.changes_made.length} changes, estimate ${rep.estimate.p_tlens_in_meta_vr_glasses}/${rep.estimate.p_meta_is_qtech_backed_oem}`)

phase('Critique')
let critic = await agent(`Completeness critic for a research dataset (today 2026-10-08) on whether poLight's TLens autofocus is designed into Meta's spring-2027 VR Glasses and how autofocus suppliers line up with AR/VR/XR launches. Read ${FILES} and ${D}/new/verification_summary.txt. The final headline findings are:\n${rep.headline_findings.map((t, i) => `[${i}] ${t}`).join('\n')}\nEstimate: ${JSON.stringify(rep.estimate)}\n\nAnswer in plain text, up to 20 lines of "gap | why it matters | how to close it (source or method)": which evidence modalities have NOT been run (e.g. teardown databases, import/export records, HKEX filings of Q Tech's subsidiaries, Oslo Børs insider trades, conference talks, job-post archives, Chinese patent legal-status, supplier-list disclosures, EU/US tariff filings), which claims in the findings rest on a single secondary source, which lanes are thin relative to their importance (give the row counts you see), and which upcoming dated events (next 6 months) would most change the estimate. Then one paragraph on the three most valuable next research tasks.`, { label: 'critic', phase: 'Critique', effort: 'high', model: 'sonnet' })
if (!critic) critic = ''
return { dropped: dropSet.size, fixed: fixes.length, issues: issues.length, blocking: blocking.length, matches: rep.matches.length, commentary_patches: (rep.commentary_patches || []).length, findings: rep.headline_findings, estimate: rep.estimate, changes: rep.changes_made, critique_preview: critic.slice(0, 3000) }
